version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      github_actions_all:
        patterns: ["*"]
    commit-message:
      prefix: "deps"
      include: "scope"
    labels: ["dependencies"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      npm_all:
        patterns: ["*"]
    commit-message:
      prefix: "deps"
      include: "scope"
    labels: ["dependencies"]

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      pip_all:
        patterns: ["*"]
    commit-message:
      prefix: "deps"
      include: "scope"
    labels: ["dependencies"]

  - package-ecosystem: "terraform"
    directory: "/deployment/otc"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      terraform_all:
        patterns: ["*"]
    commit-message:
      prefix: "deps"
      include: "scope"
    labels: ["dependencies"]

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      docker_backend:
        patterns: ["*"]
    commit-message:
      prefix: "deps"
      include: "scope"
    labels: ["dependencies"]

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      docker_frontend:
        patterns: ["*"]
    commit-message:
      prefix: "deps"
      include: "scope"
    labels: ["dependencies"]
